spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
  cache:
    type: redis
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
   metrics:
    export:
     url: http://jaeger:4318/v1/metrics
     enabled: true
