spring:
  main:
    web-application-type: reactive
  data:
    redis:
      host: redis
      port: 6379
      password: ${redis.password}
      sentinel:
        master: redis-master
        nodes:
          - sentinel-1:26379
          - sentinel-2:26380
          - sentinel-3:26381
      lettuce:
        shutdown-timeout: 200ms
  cache:
    type: redis
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
   tracing:
    endpoint: http://jaeger:4318/v1/traces