spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-path: ${server.servlet.context-path:}/actuator/health
        health-check-interval: 15s
        health-check-timeout: 90s
        health-check-critical-timeout: 3m
        instanceId: "${spring.application.name}:${random.int[1,999999]}"
        instanceZone: zone1
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

rabbit:
  event:
    queue: q.event-queue

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"  
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces

server:
  port: 0