spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
rabbit:
  event:
    queue: q.event-queue
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"  
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
   metrics:
    export:
     url: http://localhost:4318/v1/metrics
     enabled: true
